String appLogo = 'assets/images/logo2.jpg';
String pdfUrl =
    'https://firebasestorage.googleapis.com/v0/b/hstest-d4624.appspot.com/o/Updated%20Time%20table%2001-06-2023.pdf?alt=media&token=25d5814d-b010-4207-984d-e074b8fa0ce3';
String pdfUrl2 =
    'https://pctb.punjab.gov.pk/system/files/final%20PTB%20Pakistan%20studies%2010%20EM%20prepress%2008-02-2020_0.pdf';
String pptUrl =
    'https://firebasestorage.googleapis.com/v0/b/hstest-d4624.appspot.com/o/Lec%2001.ppt?alt=media&token=75dedf61-4ca8-44ef-968c-87d31dcf6e8e';
String dummytext =
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce auctor sem nec eros tristique, vitae ultrices est bibendum. Quisque id enim sit amet erat iaculis sollicitudin. Curabitur scelerisque tincidunt augue, vel consequat lorem consectetur vel. Sed et lectus leo. In sit amet ullamcorper ipsum. Mauris efficitur aliquam diam a tempus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ut mollis sem. Sed fringilla arcu nec diam facilisis, sit amet dictum metus luctus. Mauris tristique, neque id bibendum dictum, ipsum turpis ullamcorper felis, eget vestibulum risus mi id nulla. Cras eu dolor aliquam, vestibulum erat eget, aliquam est.Nulla vitae erat interdum, tincidunt purus vitae, auctor metus. Proin vestibulum ante eget sem finibus, eu laoreet odio luctus. Sed id velit non orci tempor semper et at urna. Donec posuere sem vitae lorem cursus lacinia. Nullam pulvinar, odio id varius viverra, odio elit lobortis ligula, non venenatis mi tellus eu risus. Quisque malesuada convallis dolor. Fusce auctor hendrerit ante eu luctus. Praesent convallis sapien dui, id vestibulum sem dictum nec. Nunc ullamcorper, sem non malesuada fringilla, nulla tortor faucibus tortor, ac ultricies tortor nulla id risus. Curabitur varius leo non augue pharetra, eu tincidunt purus sollicitudin. Mauris facilisis orci nec nulla hendrerit, a pretium est feugiat.";
